"""empty message

Revision ID: 74f13b2c5147
Revises: c11758faf14e
Create Date: 2019-08-29 16:46:39.226587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f13b2c5147'
down_revision = 'c11758faf14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('opportunity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'opportunity')
    # ### end Alembic commands ###
